### ISSUE TITLE
Naming the fork ⑂

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/sunog#1]
Hopefully not out of line here - but seeing as:

- I have more time to maintain the library
- The new API involved basically a rewrite
- Have even more awesome plans for next releases
- Don't currently have the ability to make releases on existing project
- The library is quite young and user base is not large

It may be time to just fork.

But in order to push releases to Clojars, we'll need a new name...

@martinklepsch have any name ideas? 

Perhaps a word with fiery meaning, ie. likely to have been used to name a totally unrelated project:

- igneus
- pyre
- conflagrate (lispy cute, but nah)

Or a cool sounding translation into a language we don't speak:

- umlilo (zulu)
- sunog (filipino)

Indonesian translation is "api", which is quite cute, but not very usable :)

*Or perhaps a less literal, imaginative memorable name. With a mascot. :dolphin:*

@verma you're welcome to merge my changes back into pani, and I may come back if pace picks up - or you could even *join the dark side*.

**Comment by verma** [comment]
I understand, sorry for being totally unresponsive.   You are right I've been struggling to find time.  If you want I can transfer the repo over as well.  Not sure about clojars though.

**Comment by crisptrutski** [comment]
Thanks, glad I haven't offended you! Obviously this wouldn't be here without your work, and I'm not trying to steal fire from the gods, because that guy did not have a good time. 

Not familiar with workflow in Github for moving to a "project" repo, but perhaps that'd be the best option. Will see how our (1 known) user feels about name change.

**Comment by verma** [comment]
No problem!  I am mostly just concerned about the Clojure community and I feel this is the right thing to do.

The name sounds awesome, guess I could add a note on pani mentioning that the new fork is the place for much fun :)

**Comment by crisptrutski** [comment]
OK great - yes a forwarding link would be awesome.

Hope you have more time in the future to jump back in here, or we can find something else to collaborate on :octocat:

**Comment by verma** [comment]
Agree :)

**Comment by martinklepsch** [comment]
```
firebase |ˈfīrˌbāsˈfaɪrbeɪs|
noun
an area in a war zone in which artillery can be massed to provide heavy firepower in support of other military units.
```
I wonder if there are some interesting possibilities around that for names.
Other than that I don't really have any suggestions I'm afraid.

**Comment by crisptrutski** [comment]
Ha! Had no idea. Yeah perhaps a super militant or jarringly peace-brokering name would work :)

**Comment by crisptrutski** [comment]
Came across the phrase "flying stovepipe" when looking into artillery, liking that :rocket:

**Comment by crisptrutski** [comment]
So `panoply` could make sense on a few levels, and sounds.. familiar

**Comment by martinklepsch** [comment]
Things in the direction of matches or fuse would also make sense. Maybe an
old brand of matches with a nice old looking illustration for the readme

On Sunday, February 15, 2015, Chris Truter <notifications@github.com> wrote:

> So panoply could make sense on a few levels, and sounds.. familiar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crisptrutski/sunog/issues/1#issuecomment-74426759>.
>


-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>

**Comment by crisptrutski** [comment]
Sounds hipster ;) You've got me dreaming of action and armaments though, not sure how to medaite them..  http://bit.ly/1AFv8bK

**Comment by martinklepsch** [comment]
Just name it `matchbox`. That's it!

**Comment by crisptrutski** [comment]
Aww man, but I just got these badges made for the current name.. http://bit.ly/1CxjfDM

Thanks for the help - yeah also really like Matchbox. Now we just need a demo app that's a multi-player micro car racer.

Not sure if you saw this: http://bit.ly/1AbSvaU (could be a good way to market this library)

**Comment by crisptrutski** [comment]
@martinklepsch #3 is almost done, so now it's really a matter of updating the docs.. and maybe working on a killer demo app, perhaps nested in a microsite.. want to get more involved? :jack_o_lantern:

**Comment by martinklepsch** [comment]
I'm pretty busy for at least another week preparing a CLJS workshop (which will use pani or sunog/matchbox?).

Maybe the app I'm preparing for that would be an interesting starting point for a demo app. It's basically a chat app with some basic authentication stuff.

**Comment by crisptrutski** [comment]
That's really awesome Martin - interested in seeing materials from your workshop, and excited this 'lil lib is getting in on the action. Having a demo app like that for the library will be great documentation, promotion, and feel out any serious shortcomings (haven't had a chance to use this baby in anger myself really)

Have some time this evening- going to finish and cut the 0.0.5 release, which is mostly CLJ oriented unfortunately, but will also slap on the matchbox branding :fire: 

Will look at a basic solution for #7 - that seems quite crucial for chat if you want server to retain full logs but only get say last 5 messages or 10 minutes messages for new clients connecting. Or shadow ban users :ghost:
