### ISSUE TITLE
Connectivity management and disconnection hooks

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/sunog#4]

**Comment by crisptrutski** [comment]
Thinking of managing the disconnection hooks like a map-in-an-atom, to hid "setters + reset" interface below.

**Comment by crisptrutski** [comment]
So just wrapping the interop would look like this:

```clojure
(let [hook (on-disconnect ref)]
   (p/reset! hook 1)
   (p/cancel! hook)
   (p/swap! hook inc))
```

@martinklepsch so obviously I'd want to wave a magic-macro wand

```clojure
(p/on-disconnect
  (p/reset! 1)
  (p/swap! inc))
```

Guess you could just promise `(<- ..)` in the README though :wink: 

Or it could just be a regular function, and turn the callbacks into data:

```clojure
(p/on-disconnect
  [:reset 1 call-back]
  [:swap inc])
```

(Have no idea why you'd want to have more than one of these callbacks by the way.. maybe we just want `sunog.disconnect/reset!` and friends)

On to more serious concerns, perhaps the whole mutable-local-state of disconnects-on-refs should be abstracted away or made more explicit.

Assuming for the moment we have a macro like above, we could forego a https://www.firebase.com/docs/web/api/ondisconnect/cancel.html method for `(p/add-disconnect-hooks! ref..`) and `(p/reset-disconnect-hooks! ref ...`) version, where arguments after ref to latter can be omitted. Once issue here though is that the underlying `cancel` is cascading..

Now backing off my the macro madness, it would be great to just lift all the `set(-with-priority)!`, `update!` and `remove!` callbacks to a single data structure, with paths matching the firebase key segments. 

Not sure how easy it is to extract this data from the refs (say, it was already created by Javascript), although probably good-enough to just expose the ones registered by this library. 

So many options..

Thoughts?

**Comment by crisptrutski** [comment]
@verma maybe you have ideas? :)

**Comment by crisptrutski** [comment]
Going with no-wrapping for 0.0.5, will revisit

**Comment by verma** [comment]
Not sure what `no-wrapping` means, but after taking a look at the docs for `onDisconnect`, I guess as a user I would like to do something like this maybe:

```
(-> (p/on-disconnect ref)
    (p/set! "Going away"))
```

so I guess I am in the camp of your first approach :).

**Comment by crisptrutski** [comment]
Yeah, here's usage from the tests, just as you post: `(-> ref p/on-disconnect p/remove!)`.

What I don't like about this approach is that the disconnection logic is hidden in the refs - you can set them on specific nodes, and clear them on nodes and their children - feels like this state should be epochal and global to be clojuristic.

To make things specific, pseudo-future-code:

```clojure
(p/disconnect-hooks user-ref)
;; => {:connected {:_set [5, callback-fn]}}
(p/add-disconnect-hook! (p/get-in user-ref :disconnected-at)
   :set p/SERVER_TIMESTAMP)
(p/disconnect-hooks user-ref)
;; => {:connected {:_set [5, callback-fn]}, :disconnected-at {:set [p/SERVER_TIMESTAMP]}
```

Having the disconnects as data would be great for debugging, and possibly to allow more powerful or scoped adding and deletion (ie. walk refs according to X logic and set key Y to Z on disconnect, or to provide a more explicit example using cancellation - find these N documents under documents-ref, and remove the `remove` hook on them, because this anonymous user just shared them with a paid user).
