### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/sunog#5]
Firebase supports 

1: authorizing by a number of means
2. info on session (`uid`, how you authenticated, when session expires, etc)
3. terminating a session

Not interested in supporting all the auth mechanism to start, but can get far with just supporting anonymous and password based auth (and common to both platforms)

**Comment by tomisme** [comment]
I'm currently building an application that will eventually use Google authentication and firebase, I'm happy to have a crack at Google auth support.

**Comment by crisptrutski** [comment]
@tomisme thanks!

Adding some docs around auth using Matchbox would be great too (even though it's a pretty thinwrapper around the clients)
